import { Student, Company, PlacementDrive, Activity } from './types';

export const students: Student[] = [
  {
    id: '1',
    name: 'Rahul Sharma',
    rollNumber: 'CSE2021001',
    email: 'rahul.sharma@college.edu',
    phone: '+91 9876543210',
    branch: 'CSE',
    cgpa: 8.5,
    skills: ['React', 'Node.js', 'Python', 'Machine Learning'],
    placementStatus: 'placed',
    company: 'Google',
    package: 2500000,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Priya Patel',
    rollNumber: 'ECE2021002',
    email: 'priya.patel@college.edu',
    phone: '+91 9876543211',
    branch: 'ECE',
    cgpa: 9.2,
    skills: ['VLSI', 'Embedded Systems', 'C++', 'Arduino'],
    placementStatus: 'placed',
    company: 'Intel',
    package: 1800000,
    createdAt: '2024-01-16',
  },
  {
    id: '3',
    name: 'Amit Kumar',
    rollNumber: 'CSE2021003',
    email: 'amit.kumar@college.edu',
    phone: '+91 9876543212',
    branch: 'CSE',
    cgpa: 7.8,
    skills: ['Java', 'Spring Boot', 'MySQL', 'AWS'],
    placementStatus: 'unplaced',
    createdAt: '2024-01-17',
  },
  {
    id: '4',
    name: 'Sneha Reddy',
    rollNumber: 'IT2021004',
    email: 'sneha.reddy@college.edu',
    phone: '+91 9876543213',
    branch: 'IT',
    cgpa: 8.9,
    skills: ['Angular', 'TypeScript', 'MongoDB', 'Docker'],
    placementStatus: 'placed',
    company: 'Microsoft',
    package: 2200000,
    createdAt: '2024-01-18',
  },
  {
    id: '5',
    name: 'Vikram Singh',
    rollNumber: 'MECH2021005',
    email: 'vikram.singh@college.edu',
    phone: '+91 9876543214',
    branch: 'MECH',
    cgpa: 7.2,
    skills: ['AutoCAD', 'SolidWorks', 'MATLAB', 'CNC Programming'],
    placementStatus: 'unplaced',
    createdAt: '2024-01-19',
  },
  {
    id: '6',
    name: 'Ananya Gupta',
    rollNumber: 'CSE2021006',
    email: 'ananya.gupta@college.edu',
    phone: '+91 9876543215',
    branch: 'CSE',
    cgpa: 9.5,
    skills: ['Python', 'TensorFlow', 'Deep Learning', 'NLP'],
    placementStatus: 'placed',
    company: 'Amazon',
    package: 2800000,
    createdAt: '2024-01-20',
  },
  {
    id: '7',
    name: 'Rohan Mehta',
    rollNumber: 'EEE2021007',
    email: 'rohan.mehta@college.edu',
    phone: '+91 9876543216',
    branch: 'EEE',
    cgpa: 6.8,
    skills: ['Power Systems', 'PLC Programming', 'SCADA'],
    placementStatus: 'not-eligible',
    createdAt: '2024-01-21',
  },
  {
    id: '8',
    name: 'Kavya Nair',
    rollNumber: 'IT2021008',
    email: 'kavya.nair@college.edu',
    phone: '+91 9876543217',
    branch: 'IT',
    cgpa: 8.1,
    skills: ['Vue.js', 'GraphQL', 'PostgreSQL', 'Kubernetes'],
    placementStatus: 'unplaced',
    createdAt: '2024-01-22',
  },
  {
    id: '9',
    name: 'Arjun Verma',
    rollNumber: 'CIVIL2021009',
    email: 'arjun.verma@college.edu',
    phone: '+91 9876543218',
    branch: 'CIVIL',
    cgpa: 7.5,
    skills: ['AutoCAD', 'STAAD Pro', 'Revit', 'Project Management'],
    placementStatus: 'placed',
    company: 'L&T',
    package: 800000,
    createdAt: '2024-01-23',
  },
  {
    id: '10',
    name: 'Meera Iyer',
    rollNumber: 'ECE2021010',
    email: 'meera.iyer@college.edu',
    phone: '+91 9876543219',
    branch: 'ECE',
    cgpa: 8.7,
    skills: ['Signal Processing', 'FPGA', 'Verilog', 'IoT'],
    placementStatus: 'unplaced',
    createdAt: '2024-01-24',
  },
];

export const companies: Company[] = [
  {
    id: '1',
    name: 'Google',
    industry: 'Technology',
    website: 'https://google.com',
    contactPerson: 'John Smith',
    contactEmail: 'hr@google.com',
    contactPhone: '+1 650-253-0000',
    jobRoles: ['Software Engineer', 'Product Manager', 'Data Scientist'],
    packageOffered: { min: 2000000, max: 3500000 },
    visitHistory: [
      { date: '2024-01-15', studentsHired: 5 },
      { date: '2023-01-20', studentsHired: 4 },
    ],
    createdAt: '2023-01-01',
  },
  {
    id: '2',
    name: 'Microsoft',
    industry: 'Technology',
    website: 'https://microsoft.com',
    contactPerson: 'Sarah Johnson',
    contactEmail: 'campus@microsoft.com',
    contactPhone: '+1 425-882-8080',
    jobRoles: ['Software Developer', 'Cloud Engineer', 'AI Researcher'],
    packageOffered: { min: 1800000, max: 3000000 },
    visitHistory: [
      { date: '2024-02-10', studentsHired: 8 },
      { date: '2023-02-15', studentsHired: 6 },
    ],
    createdAt: '2023-01-02',
  },
  {
    id: '3',
    name: 'Amazon',
    industry: 'E-commerce/Technology',
    website: 'https://amazon.com',
    contactPerson: 'Mike Chen',
    contactEmail: 'university@amazon.com',
    contactPhone: '+1 206-266-1000',
    jobRoles: ['SDE', 'Operations Manager', 'Data Engineer'],
    packageOffered: { min: 2200000, max: 4000000 },
    visitHistory: [
      { date: '2024-01-25', studentsHired: 12 },
    ],
    createdAt: '2023-01-03',
  },
  {
    id: '4',
    name: 'Intel',
    industry: 'Semiconductors',
    website: 'https://intel.com',
    contactPerson: 'Emily Davis',
    contactEmail: 'recruitment@intel.com',
    contactPhone: '+1 408-765-8080',
    jobRoles: ['Hardware Engineer', 'VLSI Designer', 'Firmware Developer'],
    packageOffered: { min: 1500000, max: 2500000 },
    visitHistory: [
      { date: '2024-02-05', studentsHired: 6 },
    ],
    createdAt: '2023-01-04',
  },
  {
    id: '5',
    name: 'TCS',
    industry: 'IT Services',
    website: 'https://tcs.com',
    contactPerson: 'Rajesh Kumar',
    contactEmail: 'campus.recruitment@tcs.com',
    contactPhone: '+91 22-6778-9999',
    jobRoles: ['Software Developer', 'Business Analyst', 'System Engineer'],
    packageOffered: { min: 400000, max: 700000 },
    visitHistory: [
      { date: '2024-01-10', studentsHired: 45 },
      { date: '2023-01-12', studentsHired: 50 },
    ],
    createdAt: '2023-01-05',
  },
  {
    id: '6',
    name: 'Infosys',
    industry: 'IT Services',
    website: 'https://infosys.com',
    contactPerson: 'Priya Sharma',
    contactEmail: 'campus@infosys.com',
    contactPhone: '+91 80-2852-0261',
    jobRoles: ['Systems Engineer', 'Digital Specialist', 'Consultant'],
    packageOffered: { min: 380000, max: 650000 },
    visitHistory: [
      { date: '2024-02-01', studentsHired: 38 },
    ],
    createdAt: '2023-01-06',
  },
  {
    id: '7',
    name: 'L&T',
    industry: 'Construction/Engineering',
    website: 'https://larsentoubro.com',
    contactPerson: 'Arun Patel',
    contactEmail: 'hr@larsentoubro.com',
    contactPhone: '+91 22-6752-5656',
    jobRoles: ['Civil Engineer', 'Project Manager', 'Mechanical Engineer'],
    packageOffered: { min: 600000, max: 1200000 },
    visitHistory: [
      { date: '2024-01-28', studentsHired: 15 },
    ],
    createdAt: '2023-01-07',
  },
  {
    id: '8',
    name: 'Flipkart',
    industry: 'E-commerce',
    website: 'https://flipkart.com',
    contactPerson: 'Neha Gupta',
    contactEmail: 'campus@flipkart.com',
    contactPhone: '+91 80-4349-0000',
    jobRoles: ['Software Engineer', 'Product Analyst', 'Supply Chain Analyst'],
    packageOffered: { min: 1600000, max: 2800000 },
    visitHistory: [
      { date: '2024-02-08', studentsHired: 7 },
    ],
    createdAt: '2023-01-08',
  },
];

export const placementDrives: PlacementDrive[] = [
  {
    id: '1',
    companyId: '1',
    companyName: 'Google',
    jobRole: 'Software Engineer',
    date: '2024-03-15',
    eligibleBranches: ['CSE', 'IT', 'ECE'],
    minCgpa: 8.0,
    packageOffered: 2500000,
    status: 'upcoming',
    registeredStudents: 45,
    selectedStudents: 0,
    description: 'Google is hiring Software Engineers for their Bangalore office. Strong problem-solving skills required.',
    createdAt: '2024-02-01',
  },
  {
    id: '2',
    companyId: '2',
    companyName: 'Microsoft',
    jobRole: 'Software Developer',
    date: '2024-03-10',
    eligibleBranches: ['CSE', 'IT'],
    minCgpa: 7.5,
    packageOffered: 2200000,
    status: 'upcoming',
    registeredStudents: 52,
    selectedStudents: 0,
    description: 'Microsoft is looking for passionate developers to join their Azure team.',
    createdAt: '2024-02-02',
  },
  {
    id: '3',
    companyId: '5',
    companyName: 'TCS',
    jobRole: 'System Engineer',
    date: '2024-02-28',
    eligibleBranches: ['CSE', 'IT', 'ECE', 'EEE', 'MECH'],
    minCgpa: 6.0,
    packageOffered: 450000,
    status: 'ongoing',
    registeredStudents: 180,
    selectedStudents: 45,
    description: 'TCS National Qualifier Test followed by interviews.',
    createdAt: '2024-01-15',
  },
  {
    id: '4',
    companyId: '3',
    companyName: 'Amazon',
    jobRole: 'SDE-1',
    date: '2024-01-25',
    eligibleBranches: ['CSE', 'IT'],
    minCgpa: 7.0,
    packageOffered: 2800000,
    status: 'completed',
    registeredStudents: 68,
    selectedStudents: 12,
    description: 'Amazon campus drive for fresh graduates.',
    createdAt: '2024-01-01',
  },
  {
    id: '5',
    companyId: '4',
    companyName: 'Intel',
    jobRole: 'Hardware Engineer',
    date: '2024-02-05',
    eligibleBranches: ['ECE', 'EEE'],
    minCgpa: 7.5,
    packageOffered: 1800000,
    status: 'completed',
    registeredStudents: 35,
    selectedStudents: 6,
    description: 'Intel hiring for their chip design team.',
    createdAt: '2024-01-10',
  },
  {
    id: '6',
    companyId: '7',
    companyName: 'L&T',
    jobRole: 'Graduate Engineer Trainee',
    date: '2024-03-20',
    eligibleBranches: ['CIVIL', 'MECH', 'EEE'],
    minCgpa: 6.5,
    packageOffered: 800000,
    status: 'upcoming',
    registeredStudents: 28,
    selectedStudents: 0,
    description: 'L&T infrastructure division recruitment.',
    createdAt: '2024-02-10',
  },
  {
    id: '7',
    companyId: '8',
    companyName: 'Flipkart',
    jobRole: 'Software Engineer',
    date: '2024-02-08',
    eligibleBranches: ['CSE', 'IT'],
    minCgpa: 7.0,
    packageOffered: 2000000,
    status: 'completed',
    registeredStudents: 55,
    selectedStudents: 7,
    description: 'Flipkart hiring for their tech team.',
    createdAt: '2024-01-20',
  },
];

export const recentActivities: Activity[] = [
  {
    id: '1',
    type: 'placement',
    message: 'Ananya Gupta got placed at Amazon with 28 LPA package',
    timestamp: '2024-02-15T10:30:00',
  },
  {
    id: '2',
    type: 'drive',
    message: 'Google placement drive scheduled for March 15, 2024',
    timestamp: '2024-02-14T15:45:00',
  },
  {
    id: '3',
    type: 'registration',
    message: '45 students registered for Microsoft placement drive',
    timestamp: '2024-02-14T09:20:00',
  },
  {
    id: '4',
    type: 'company',
    message: 'Flipkart added as new recruiting partner',
    timestamp: '2024-02-13T14:00:00',
  },
  {
    id: '5',
    type: 'placement',
    message: '12 students selected in Amazon campus drive',
    timestamp: '2024-02-12T16:30:00',
  },
  {
    id: '6',
    type: 'drive',
    message: 'TCS drive status updated to ongoing',
    timestamp: '2024-02-11T11:15:00',
  },
];

export const analyticsData = {
  branchWisePlacement: [
    { branch: 'CSE', placed: 85, total: 120 },
    { branch: 'IT', placed: 45, total: 60 },
    { branch: 'ECE', placed: 38, total: 80 },
    { branch: 'EEE', placed: 22, total: 50 },
    { branch: 'MECH', placed: 18, total: 70 },
    { branch: 'CIVIL', placed: 15, total: 40 },
  ],
  monthlyPlacements: [
    { month: 'Aug', placements: 12 },
    { month: 'Sep', placements: 25 },
    { month: 'Oct', placements: 45 },
    { month: 'Nov', placements: 38 },
    { month: 'Dec', placements: 52 },
    { month: 'Jan', placements: 65 },
    { month: 'Feb', placements: 48 },
  ],
  packageDistribution: [
    { range: '3-5 LPA', count: 85 },
    { range: '5-10 LPA', count: 65 },
    { range: '10-15 LPA', count: 35 },
    { range: '15-25 LPA', count: 28 },
    { range: '25+ LPA', count: 12 },
  ],
  topRecruiters: [
    { company: 'TCS', hires: 45 },
    { company: 'Infosys', hires: 38 },
    { company: 'Amazon', hires: 12 },
    { company: 'Microsoft', hires: 8 },
    { company: 'Flipkart', hires: 7 },
  ],
};
